version: "3"
services:
  typecho:
    build: .
    volumes:
      - ~/Desktop/tmp/typecho:/data
    ports:
      - "8000:80"
    depends_on:
      # - mysql
      - mariadb
  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: somewordpress
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_USER: wordpress
  #     MYSQL_PASSWORD: wordpress
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typecho
  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
